### ISSUE TITLE
Errors in settings.py

### ISSUE THREAD

**Issue by ksusonic** [techiediaries/django-react#22]
Hi! 
While I'm doing `python manage.py migrate` I get this:

```
SystemCheckError: System check identified some issues:

ERRORS:
?: (corsheaders.E013) Origin 'localhost:3000' in CORS_ORIGIN_WHITELIST is missing scheme or netloc
        HINT: Add a scheme (e.g. https://) or netloc (e.g. example.com).

WARNINGS:
customers.Customer: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the CustomersConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
```
